# Generated by Django 5.0.7 on 2024-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninstallment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
