# Generated by Django 5.0.7 on 2024-08-25 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loaninstallment_date_alter_loanrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
